export interface BestiaryEntry {
  id: string;
  name: string;
  subtitle: string;
  category: 'COMUM' | 'CHEFE' | 'LENDARIO';
  enemyType: 'slime' | 'goblin' | 'orc' | 'elemental' | 'boss';
  hp: number;
  mp: number;
  attack: number;
  defense: number;
  magDef: number;
  speed: number;
  exp: number;
  gold: number;
  habitat: string;
  weakness: string;
  drops: string;
  sarcasticLore: string;
  parodyTip: string;
}

export const BESTIARY_CATALOG: BestiaryEntry[] = [
  {
    id: 'slime',
    name: 'Slime Verde',
    subtitle: 'O Primeiro Inimigo de Todo RPG Desde 1986',
    category: 'COMUM',
    enemyType: 'slime',
    hp: 35,
    mp: 0,
    attack: 14,
    defense: 8,
    magDef: 8,
    speed: 5,
    exp: 35,
    gold: 8,
    habitat: 'Planicies de Cornelia e Caverna do Preludio',
    weakness: 'Fogo e qualquer pessoa que aperte o botao de ataque',
    drops: 'Pocao Simples ou Erva Antidoto',
    sarcasticLore: 'Uma gota gelatinosa de gosma verde cuja unica funcao na vida e esperar quatro herois bem armados para servir de saco de pancadas no tutorial.',
    parodyTip: 'Nao gaste seus preciosos pontos de magia aqui. Apenas aperte confirmar ate a batalha acabar.'
  },
  {
    id: 'goblin',
    name: 'Goblin Salteador',
    subtitle: 'O Mestre da Emboscada a Cada Dois Passos',
    category: 'COMUM',
    enemyType: 'goblin',
    hp: 50,
    mp: 10,
    attack: 20,
    defense: 10,
    magDef: 8,
    speed: 8,
    exp: 55,
    gold: 18,
    habitat: 'Florestas e Cavernas da Regiao de Cornelia',
    weakness: 'Gelo e armas cortantes',
    drops: 'Pocao ou Eter',
    sarcasticLore: 'Especialista em interromper sua caminhada pacifica no mapa mundi com a classica musica de batalha. Guarda 18 moedas de ouro dentro do bolso rasgado.',
    parodyTip: 'Dizem que se voce der tres passos sem encontrar um goblin, o cartucho de jogo esta com defeito.'
  },
  {
    id: 'orc',
    name: 'Orc Guerreiro',
    subtitle: 'O Goblin que Ficou Muito Bravo e Foi Para a Academia',
    category: 'COMUM',
    enemyType: 'orc',
    hp: 90,
    mp: 0,
    attack: 28,
    defense: 18,
    magDef: 10,
    speed: 6,
    exp: 100,
    gold: 40,
    habitat: 'Santuario da Terra e Monte Gulg',
    weakness: 'Magia de Fogo e Eletricidade',
    drops: 'Hi-Pocao ou Elixir',
    sarcasticLore: 'Um brutamontes verde com elmo chifrado. Nao pensa muito, apenas corre em linha reta balancando um machado de ferro.',
    parodyTip: 'Ele tem bastante defesa fisica, entao usar o Mago Negro para torrar a armadura dele poupa bastante tempo.'
  },
  {
    id: 'elemental',
    name: 'Elemental Arcano',
    subtitle: 'Esfera Flutuante de Energia que Ignora Espadadas',
    category: 'COMUM',
    enemyType: 'elemental',
    hp: 70,
    mp: 60,
    attack: 12,
    defense: 10,
    magDef: 24,
    speed: 12,
    exp: 135,
    gold: 55,
    habitat: 'Torre da Miragem e Santuario Submerso',
    weakness: 'Elemento Oposto ao da sua Cor',
    drops: 'Eter Mago ou Elixir Raro',
    sarcasticLore: 'Uma bola de fogo magica consciente que passa o dia flutuando em corredores estreitos esperando aventureiros desavisados.',
    parodyTip: 'Se ele for vermelho, use gelo. Se for azul, use fogo. A logica elementar basica dos videogames nunca falha.'
  },
  {
    id: 'boss_preludio',
    name: 'Gargula do Preludio',
    subtitle: 'Chefe de Entrada que Testa se Voce Comprou Pocoes',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 220,
    mp: 60,
    attack: 28,
    defense: 16,
    magDef: 14,
    speed: 11,
    exp: 300,
    gold: 250,
    habitat: 'Caverna do Preludio - Andar 2',
    weakness: 'Magia de Fogo e Ataques do Guerreiro',
    drops: 'Espada de Aco e Pocao Extra',
    sarcasticLore: 'Ficou petrificada por 300 anos esperando a profecia dos quatro guerreiros da luz, apenas para ser derrotada em quatro turnos.',
    parodyTip: 'Mantenha o HP do seu grupo acima de zero e ataque ate o HP dele chegar a zero.'
  },
  {
    id: 'boss_desafio',
    name: 'Cavaleiro Sombrio',
    subtitle: 'O Guarda de Honra que Nao Sai do Tapete Vermelho',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 320,
    mp: 80,
    attack: 36,
    defense: 22,
    magDef: 18,
    speed: 12,
    exp: 450,
    gold: 400,
    habitat: 'Cidadela dos Desafios - Trono',
    weakness: 'Magia Sagrada e Fogo Divino',
    drops: 'Armadura de Placas e Hi-Pocao',
    sarcasticLore: 'Guarda o trono de uma fortaleza abandonada sem receber salario desde a primeira era dos cristais.',
    parodyTip: 'Ele gosta de posar de forma imponente antes de atacar. Aproveite essa pose para curar seu time.'
  },
  {
    id: 'boss_terra',
    name: 'Lich da Terra',
    subtitle: 'O Feiticeiro Morto-Vivo com Monologo Dramatico',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 380,
    mp: 120,
    attack: 32,
    defense: 20,
    magDef: 30,
    speed: 13,
    exp: 550,
    gold: 500,
    habitat: 'Santuario da Terra - Altar Profundo',
    weakness: 'Fogo Arcano e Magia Branca de Luz',
    drops: 'Cajado do Anciao e Eter Puro',
    sarcasticLore: 'Um esqueleto com manto elegante que corrompeu o cristal da terra apenas porque nao tinha nada melhor para fazer no fim de semana.',
    parodyTip: 'Mortos-vivos odeiam fogo e magias de cura. Lance feiticos brilhantes ate ele virar po.'
  },
  {
    id: 'boss_fogo',
    name: 'Marilith de Fogo',
    subtitle: 'Seis Bracos com Seis Espadas e Zero Protetor Solar',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 480,
    mp: 130,
    attack: 45,
    defense: 24,
    magDef: 22,
    speed: 16,
    exp: 750,
    gold: 700,
    habitat: 'Monte Gulg - Nucleo de Lava',
    weakness: 'Magia de Gelo e Nevasca',
    drops: 'Espada Flamejante e Elixir',
    sarcasticLore: 'Vive dentro de um vulcano ativo e ainda reclama que o ar condicionado da masmorra esta quebrado.',
    parodyTip: 'Use Gelo 2 ou Nevasca. Se tentar usar fogo contra ela, seus companheiros de equipe vao rir de voce.'
  },
  {
    id: 'boss_agua',
    name: 'Kraken Abissal',
    subtitle: 'O Polvo Gigante que Odeia Eletricidade',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 580,
    mp: 150,
    attack: 48,
    defense: 26,
    magDef: 26,
    speed: 15,
    exp: 950,
    gold: 900,
    habitat: 'Santuario Submerso - Profundezas',
    weakness: 'Magia de Trovao e Raio Eletrico',
    drops: 'Tridente Sagrado e Perola Marinha',
    sarcasticLore: 'Dono de oito tentaculos e nenhuma piedade. Fica muito surpreso toda vez que aventureiros descobrem que agua conduz choque eletrico.',
    parodyTip: 'Lancar Trovao na agua pode ser perigoso na vida real, mas no RPG e a melhor estrategia possivel.'
  },
  {
    id: 'boss_ar',
    name: 'Tiamat dos Ceus',
    subtitle: 'O Dragao Multicabecas que Guarda o Topo da Torre',
    category: 'CHEFE',
    enemyType: 'boss',
    hp: 700,
    mp: 180,
    attack: 54,
    defense: 28,
    magDef: 30,
    speed: 18,
    exp: 1300,
    gold: 1200,
    habitat: 'Torre da Miragem - Andar Superior',
    weakness: 'Gelo, Veneno e Dano Perfurante de Flecha',
    drops: 'Arco Celestial e Manto dos Ventos',
    sarcasticLore: 'Construiu um ninho no topo de uma torre flutuante para fugir de cobradores e herois com espadas gigantes.',
    parodyTip: 'Cuidado com os sopros elementais. Mantenha seu Mago Branco acordado a todo custo.'
  },
  {
    id: 'boss_chaos',
    name: 'Chaos Supremo',
    subtitle: 'O Chefe Final com Multiplas Fases e Filosofia Temporal',
    category: 'LENDARIO',
    enemyType: 'boss',
    hp: 1000,
    mp: 300,
    attack: 68,
    defense: 38,
    magDef: 40,
    speed: 20,
    exp: 3500,
    gold: 3000,
    habitat: 'Templo do Caos - Altar do Vazio Temporal',
    weakness: 'Todas as Armas Lendarias e Determinacao do Jogador',
    drops: 'Espada Masamune e Fim de Jogo',
    sarcasticLore: 'Um lorde cosmico que viajou no tempo em um loop infinito apenas para ser desafiado por quatro herois que passaram dez horas grindando goblins.',
    parodyTip: 'Use todas as suas Hi-Pocoes e Elixires que voce guardou o jogo inteiro com medo de gastar.'
  },
  {
    id: 'mimico_bau',
    name: 'Mimico do Bau',
    subtitle: 'A Razao de Todo Jogador Ter Medo de Abrir Tesouro',
    category: 'LENDARIO',
    enemyType: 'orc',
    hp: 260,
    mp: 40,
    attack: 34,
    defense: 20,
    magDef: 16,
    speed: 14,
    exp: 280,
    gold: 600,
    habitat: 'Salas Secretas de Masmorras Antigas',
    weakness: 'Magia de Fogo e Arrependimento de Ter Aberto',
    drops: 'Ouro Dobrado e Vergonha',
    sarcasticLore: 'Disfarcado de bau dourado brilhante com lacete vermelho. Ele sabe exatamente que voce nao consegue resistir a um bau fechado.',
    parodyTip: 'Antes de abrir um bau com HP baixo, pense duas vezes. Ou apenas abra e aceite as consequencias.'
  },
  {
    id: 'cactuar_fugitivo',
    name: 'Cacto Veloz',
    subtitle: 'Da 1000 Agulhas de Dano e Foge no Turno Seguinte',
    category: 'LENDARIO',
    enemyType: 'slime',
    hp: 10,
    mp: 100,
    attack: 50,
    defense: 99,
    magDef: 99,
    speed: 99,
    exp: 2000,
    gold: 1500,
    habitat: 'Desertos Isolados do Mundo',
    weakness: 'Dano Magico Direto e Muita Sorte',
    drops: 'Elixir Dourado e Agulha Sagrada',
    sarcasticLore: 'Um cacto com bracos e pernas que danca no deserto. Se voce nao acertar ele no primeiro segundo, ele vai embora rindo da sua cara.',
    parodyTip: 'Use habilidades que nunca erram ou feche os olhos e torca para dar dano critico.'
  },
  {
    id: 'tonberry_cozinha',
    name: 'Chef da Faca Pequena',
    subtitle: 'Anda Um Centimetro Por Turno com Olhar Assassino',
    category: 'LENDARIO',
    enemyType: 'goblin',
    hp: 450,
    mp: 50,
    attack: 80,
    defense: 30,
    magDef: 30,
    speed: 3,
    exp: 1800,
    gold: 1200,
    habitat: 'Cavernas Escuras e Profundas',
    weakness: 'Ataques a Distancia e Manter Muita Distancia',
    drops: 'Faca Suprema do Chef e Oleo de Lanterna',
    sarcasticLore: 'Um ser pequenino de capa marrom carregando uma lanterna e uma faca de cortar legumes. Parece fofo ate chegar perto.',
    parodyTip: 'Se ele der tres passos na sua direcao, corra como se nao houvesse amanha.'
  }
];
